title: Chiyuan Cheng, Ph.D. # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <br> > Scientist - Coder - Thinker - Toastmasters
  <br> > Springboard Data Science Career Track 
 
  <br> > Deep Learning Specialization, deeplearning.ai  
  
  <br><a href="https://www.linkedin.com/in/chiyuancheng/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-2800773-1 # your Google Analytics tracking ID here
