title: Chiyuan Cheng, Ph.D. # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Technical Associate | Research Scientist in a Comsumer/Healthcare Company
  <br> Ph.D. in Physical Chemistry
  <br> B.S. in Pharmacy
  Udacity Data Scientist | Data Analyst Nanodegree 
  <br><br>
  <a href="https://www.linkedin.com/in/chiyuancheng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
